source 'http://rubygems.org'

gem 'rails', '3.0.7'
gem 'formtastic'
gem 'will_paginate', '~> 3.0.pre2'
gem 'devise'
gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'jquery-rails'
gem 'aws-s3'
gem 'xml-simple'
gem 'meta_where'